---
- name: Manage packages interactively
  hosts: localhost
  gather_subset:
    - '!all'
  vars_files:
    - "{{ pacpac_config_file | default('~/.config/pacpac/packages.yml') }}"
  roles:
    - differ
    - saver
    - reaper
