pacpac_packages_extra:
  - name: shfmt
  - name: libfprint
  - name: timeshift
  - name: rust
  - name: perl-email-address
  - name: virtualbox-host-dkms
  - name: linux-headers
  - name: amd-ucode
  - name: dunst
  - name: keepalived
  - name: samba
  - name: python-opencv
  - name: nwg-look
  - name: atop
  - name: okular
  - name: fwupd
  - name: fprintd
  - name: ueberzugpp
  - name: btop
  - name: linux
  - name: wiremix
  - name: bluetui
  - name: kdenlive
  - name: jdk-openjdk
  - name: element-desktop
  - name: libvncserver
  - name: ruby-kramdown
  - name: websocat
  - name: inotify-tools
  - name: evince
  - name: archlinux-contrib
  - name: movit
  - name: python-xattr
  - name: mkosi
  - name: drawio-desktop
  - name: wayvnc
  - name: uboot-tools
  - name: keepassxc
  - name: wev
  - name: impala
  - name: glances
  - name: thunderbird
  - name: vim-ale
  - name: gtop
  - name: foot
