- name: Ask user to save
  pause:
    prompt: Save extra packages? [Y/n]
  register: ans

- name: Append extra packages to config file
  lineinfile:
    path: ~/.config/pacpac/packages.yml
    line: "  - name: {{ item }}"
  loop: "{{ extra_packages }}"
  when: ans.user_input | length == 0 or ans.user_input | lower | first == 'y'
