- name: Ask user to install missing packages
  pause:
    prompt: Install missing packages? [Y/n]
  register: ans

- name: Install missing native packages
  community.general.pacman:
    name: "{{ missing_packages }}"
    state: present
  become: true
  when: ans.user_input | length == 0 or ans.user_input | lower | first == 'y'
